logging:
  level:
    root: info
  file:
    path: ${LOG_FILE_PATH:logs}

spring:
  profiles:
    active: prod
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

drive:
  parents: ${GOOGLE_DRIVE_PARENTS:default}
  key:
    path: ${GOOGLE_DRIVE_KEY_PATH:./key/drive-key.json}

export.pdf.converter: ${PDF_CONVERTER_URL:http://localhost:5000/convert}

cors:
  allowed-origins: "http://localhost:3000,www.lapbaogia.com,https://www.lapbaogia.com"