logging:
  level:
    root: info
  file:
    path: ${LOG_FILE_PATH:logs}

spring:
  profiles:
    active: prod
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

drive:
  parents: ${GOOGLE_DRIVE_PARENTS}
  key:
    path: ${GOOGLE_DRIVE_KEY_PATH}