version: '3.1'

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appnoithat
      MYSQL_USER: truongvanhuy
      MYSQL_PASSWORD: huy2000
    volumes:
      - "./database:/docker-entrypoint-initdb.d"