version: '3.1'

services:
  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appnoithat
      MYSQL_USER: truongvanhuy
      MYSQL_PASSWORD: huy2000
    volumes:
      - "./database:/docker-entrypoint-initdb.d"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_520_ci', '--default-authentication-plugin=mysql_native_password']