version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: appnoithat_dev_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: appnoithatTruongVanHuy2000
      MYSQL_DATABASE: appnoithat
      MYSQL_USER: backendnoithat
      MYSQL_PASSWORD: huy2000plvJIN46
    volumes:
      - "./database/init:/docker-entrypoint-initdb.d" # init database
      - "./database/data:/var/lib/mysql" # save data
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 30s
      timeout: 20s
      retries: 10
    networks:
      - cat
networks:
  cat:
