version: '3.1'

services:
  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appnoithat
      MYSQL_USER: truongvanhuy
      MYSQL_PASSWORD: huy2000
    volumes:
#      - "./database:/docker-entrypoint-initdb.d"
      - "/home/appnoithat/mysqlDB:/var/lib/mysql"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 120s
      timeout: 20s
      retries: 10
    networks:
      - cat
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_520_ci', '--default-authentication-plugin=mysql_native_password']

  backend:
    image: truongvanhuy2000/appnoithatbackend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cat
    environment:
        DB_HOST: db
networks:
  cat: