version: '3.7'

services:
  db:
    image: mysql:latest
    restart: unless-stopped
#    ports:
#      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: appnoithatTruongVanHuy2000
      MYSQL_DATABASE: appnoithat
      MYSQL_USER: backendnoithat
      MYSQL_PASSWORD: huy2000plvJIN46
    volumes:
      - "./database:/docker-entrypoint-initdb.d" # init database
      - "/home/appnoithat/mysqlDB:/var/lib/mysql" # save data
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 30s
      timeout: 20s
      retries: 10
    networks:
      - cat
    command: --default-authentication-plugin=mysql_native_password

  backend:
    image: truongvanhuy2000/appnoithatbackend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - cat
    depends_on:
      db:
        condition: service_healthy
    environment:
        DB_HOST: db
networks:
  cat:
