services:
  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    env_file:
      - "env/mysql.env"
    volumes:
      - "./database/init:/docker-entrypoint-initdb.d"
      - "./database/data:/var/lib/mysql"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 30s
      timeout: 20s
      retries: 10
    networks:
      - cat

  backend:
#    image: truongvanhuy2000/appnoithatbackend
    build:
      context: ./backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - cat
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "/home/huy/companylogo:/companylogo"
    env_file:
      - "env/backend.env"

#  phpmyadmin:
#    image : phpmyadmin:latest
#    restart: unless-stopped
#    ports:
#      - "8081:80"
#    env_file:
#      - "env/phpmyadmin.env"
#    networks:
#      - cat
#    depends_on:
#      db:
#        condition: service_healthy
networks:
  cat:
