name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # buildJava:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up JDK 17
  #     uses: actions/setup-java@v3
  #     with:
  #       java-version: '17'
  #       distribution: 'temurin'
  #       cache: maven
  #   - name: Cache the Maven packages to speed up build
  #     uses: actions/cache@v1
  #     with:
  #       path: ~/.m2
  #       key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
  #       restore-keys: ${{ runner.os }}-m2   
    
  #   - run: mvn -B package -DskipTests --file pom.xml
        
  # publish-job:
  #     runs-on: ubuntu-latest
  #     needs: [buildJava]
  #     steps:
  #       - uses: actions/checkout@v2
  #       - uses: actions/setup-java@v1
  #         with:
  #           java-version: 17
  #       - run: mvn -B package --file pom.xml -DskipTests
  #       - run: mkdir staging && cp target/*.jar staging
  #       - uses: actions/upload-artifact@v1
  #         with:
  #           name: Package
  #           path: staging
      
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.SECRET_RECIPE }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: out/docker/backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/appnoithatbackend:latest

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Run makefile script
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.HOSTPORT }}
        command_timeout: 30m
        script: | 
          cd /home/appnoithat/appnoithatbackend/out/docker && make start 
